"""empty message

Revision ID: 37ea9ee14675
Revises: None
Create Date: 2016-10-24 14:03:13.131188

"""

# revision identifiers, used by Alembic.
revision = '37ea9ee14675'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DLC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('canonical_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DLC_canonical_name'), 'DLC', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_DLC_display_name'), 'DLC', ['display_name'], unique=False)
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mit_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_mit_id'), 'author', ['mit_id'], unique=True)
    op.create_index(op.f('ix_author_name'), 'author', ['name'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_handle'), 'document', ['handle'], unique=True)
    op.create_index(op.f('ix_document_title'), 'document', ['title'], unique=False)
    op.create_table('document_author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_dlc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('dlc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dlc_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_dlc')
    op.drop_table('document_author')
    op.drop_index(op.f('ix_document_title'), table_name='document')
    op.drop_index(op.f('ix_document_handle'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_author_name'), table_name='author')
    op.drop_index(op.f('ix_author_mit_id'), table_name='author')
    op.drop_table('author')
    op.drop_index(op.f('ix_DLC_display_name'), table_name='DLC')
    op.drop_index(op.f('ix_DLC_canonical_name'), table_name='DLC')
    op.drop_table('DLC')
    ### end Alembic commands ###
